blueprintapp/blueprints/people/models.py
from blueprintapp.app import db

class Person(db.Model):
  __tablename__ = 'people'
  
  pid = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String, nullable=False)
  age = db.Column(db.Integer)
  job = db.Column(db.String)
  
  def __repr__(self):
    return f"<PERSON {self.name}, Age: {self.age}>"
  
  def get_id(self):
    return self.pid

blueprintapp/blueprints/people/routes.py
from flask import request, render_template, redirect, url_for, Blueprint

from blueprintapp.app import db
from blueprintapp.blueprints.people.models import Person

people = Blueprint('people', __name__, template_folder='templates')

@people.route('/')
def index():
  people = Person.query.all()
  return render_template('people/index.html', people=people)

@people.route('/create', methods=['GET', 'POST'])
def create():
  if request.method == 'GET':
    return render_template('people/create.html')
  elif request.method == 'POST':
    name = request.form.get('name')
    age = int(request.form.get('age'))
    job = request.form.get('job')
    
    job = job if job != '' else None
    
    person = Person(name=name, age=age, job=job)
    
    db.session.add(person)
    db.session.commit()
    
    return redirect(url_for('people.index'))

blueprintapp/blueprints/people/templates/people/create.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Person</h1>
  <form action="{{url_for('people.create')}}" method='POST'>
    <input type="text" name="name" placeholder="Name" required='required'>
    <input type="number" name="age" placeholder="Age">
    <input type="text" name="job" placeholder='Job'> 
    <input type="submit" value='Create'>
  </form>
{% endblock %}

blueprintapp/blueprints/people/templates/people/index.html
{% extends "base.html" %}

{% block content %}
  <ul>
    {% for person in people %}
      <li>{{person}}</li>
    {% endfor %}
  </ul>
  <a href="{{url_for('people.create')}}">Create</a>
{% endblock %}